Stop using --sys-prefix in conda recipe
I am not quite sure what is going on. On windows, after installing `sos-notebook` through

```
conda install sos-notebook -c conda-forge
```
SoS failed to start, with an error message

```
        proc = Popen(cmd, **kwargs)
      File "C:\Users\bpeng1\AppData\Local\Continuum\anaconda3\envs\sos_r\lib\subprocess.py", line 775, in __init__
        restore_signals, start_new_session)
      File "C:\Users\bpeng1\AppData\Local\Continuum\anaconda3\envs\sos_r\lib\subprocess.py", line 1178, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
```

Digging deeper, the problem is caused by the path to python `  "C:/Users/bpeng1/AppData/Local/Continuum/anaconda3/envs/sos_r/bin/python"` in the kernel spec file

```
(sos_r) C:\Users\bpeng1\sos>jupyter kernelspec list --json
{
  "kernelspecs": {
    "ir": {
      "resource_dir": "C:\\Users\\bpeng1\\AppData\\Local\\Continuum\\anaconda3\\envs\\sos_r\\share\\jupyter\\kernels\\ir",
      "spec": {
        "argv": [
          "R",
          "--slave",
          "-e",
          "IRkernel::main()",
          "--args",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "R",
        "language": "R",
        "interrupt_mode": "signal",
        "metadata": {}
      }
    },
    "python3": {
      "resource_dir": "C:\\Users\\bpeng1\\AppData\\Local\\Continuum\\anaconda3\\envs\\sos_r\\share\\jupyter\\kernels\\python3",
      "spec": {
        "argv": [
          "C:/Users/bpeng1/AppData/Local/Continuum/anaconda3/envs/sos_r\\python.exe",
          "-m",
          "ipykernel_launcher",
          "-f",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "Python 3",
        "language": "python",
        "interrupt_mode": "signal",
        "metadata": {}
      }
    },
    "sos": {
      "resource_dir": "C:\\Users\\bpeng1\\AppData\\Local\\Continuum\\anaconda3\\envs\\sos_r\\share\\jupyter\\kernels\\sos",
      "spec": {
        "argv": [
          "C:/Users/bpeng1/AppData/Local/Continuum/anaconda3/envs/sos_r/bin/python",
          "-m",
          "sos_notebook.kernel",
          "-f",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "SoS",
        "language": "sos",
        "interrupt_mode": "signal",
        "metadata": {}
      }
    }
  }
}

```

Now, if I rerun

```
python -m sos_notebook.install
```
as done at the sos-notebook recipe [here](https://github.com/conda-forge/sos-notebook-feedstock/blob/37869ed86fb4d96ad6ad5fcabb0cad248a231990/recipe/meta.yaml#L17). The kernel spec has a different path
 
```
(sos_r) C:\Users\bpeng1\sos>jupyter kernelspec list --json
{
  "kernelspecs": {
    "sos": {
      "resource_dir": "C:\\Users\\bpeng1\\AppData\\Roaming\\jupyter\\kernels\\sos",
      "spec": {
        "argv": [
          "C:\\Users\\bpeng1\\AppData\\Local\\Continuum\\anaconda3\\envs\\sos_r\\python.exe",
          "-m",
          "sos_notebook.kernel",
          "-f",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "SoS",
        "language": "sos",
        "interrupt_mode": "signal",
        "metadata": {}
      }
    },
```

and the sos kernel is now usable. It appears necessary to remove `--sys-prefix`.